sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "stable"

branches:
  except:
    - gh-pages

after_script:
  - if [[ `node --version` == *v6* ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
